# Generated by Django 5.1.2 on 2025-11-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('business', 'ビジネス'), ('novel', '小説'), ('comic', '漫画'), ('life', '生活'), ('other', 'その他')], max_length=100),
        ),
    ]
